version: "3.9"

services:
  frontend:
    image: '$AND_DOCKER_REGISTRY_NAME/$PROJECT-$APP:$CI_COMMIT_BRANCH'
    container_name: ${APP}
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/devops/nginx/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - /home/devops/nginx/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    networks:
      - insurance
    
networks:
  insurance:
    external: true
